/* Generated by Nim Compiler v2.0.2 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\Tools\nim-2.0.2\dist\mingw64\bin\gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -Os -fno-ident   -IC:\Tools\nim-2.0.2\lib -IC:\Projekte\nim\nim_tests -o C:\Users\matth\nimcache\examples_r\@mexamples.nim.c.o C:\Users\matth\nimcache\examples_r\@mexamples.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <stdio.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__Uepftf2kOzjjb8MCOsPz7Q tySequence__Uepftf2kOzjjb8MCOsPz7Q;
typedef struct tySequence__Uepftf2kOzjjb8MCOsPz7Q_Content tySequence__Uepftf2kOzjjb8MCOsPz7Q_Content;
typedef struct tyObject_Fun__fFNWcP7BMMhEVk5tZCIemQ tyObject_Fun__fFNWcP7BMMhEVk5tZCIemQ;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NimStringV2 tyArray__nHXaesL0DJZHyVS07ARPRA[1];
typedef NimStringV2 tyArray__24KAM9afIUgUaqBaEBB6r9bg[3];
struct tySequence__Uepftf2kOzjjb8MCOsPz7Q {
  NI len; tySequence__Uepftf2kOzjjb8MCOsPz7Q_Content* p;
};
typedef NU8 tyEnum_FunKind__TZS0hMfMqAU079bFb3WWuFQ;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc__HzVCwACFYM9cx9aV62PdjtuA;
typedef N_NOCONV_PTR(void, tyProc__vhjNbzH0Mvv2fTvoe1717Q) (void);
struct tyObject_Fun__fFNWcP7BMMhEVk5tZCIemQ {
	tyEnum_FunKind__TZS0hMfMqAU079bFb3WWuFQ kind;
union{
	tyProc__HzVCwACFYM9cx9aV62PdjtuA fun1;
	tyProc__vhjNbzH0Mvv2fTvoe1717Q fun2;
};
};
struct tySequence__Uepftf2kOzjjb8MCOsPz7Q_Content { NI cap; tyObject_Fun__fFNWcP7BMMhEVk5tZCIemQ data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringV2* args_p0, NI args_p0Len_0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, readLine__stdZsyncio_u479)(FILE* f_p0);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_BOOL, equalMem__system_u1753)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZexitprocs_u301)(tySequence__Uepftf2kOzjjb8MCOsPz7Q dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsToolsatsnimminus2dot0dot2atslibatsstdatsexitprocsdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsToolsatsnimminus2dot0dot2atslibatsstdatssynciodotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsToolsatsnimminus2dot0dot2atslibatsstdatssynciodotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsToolsatsnimminus2dot0dot2atslibatssystemdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__DQXbay9bVPbJntbw5acsx2A_3 = { 18 | NIM_STRLIT_FLAG, "What\'s your name\? " };
static const struct {
  NI cap; NIM_CHAR data[30+1];
} TM__DQXbay9bVPbJntbw5acsx2A_5 = { 30 | NIM_STRLIT_FLAG, "Poor soul, you lost your name\?" };
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__DQXbay9bVPbJntbw5acsx2A_6 = { 4 | NIM_STRLIT_FLAG, "name" };
static const NimStringV2 TM__DQXbay9bVPbJntbw5acsx2A_7 = {4, (NimStrPayload*)&TM__DQXbay9bVPbJntbw5acsx2A_6};
static const struct {
  NI cap; NIM_CHAR data[30+1];
} TM__DQXbay9bVPbJntbw5acsx2A_9 = { 30 | NIM_STRLIT_FLAG, "Very funny, your name is name." };
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__DQXbay9bVPbJntbw5acsx2A_10 = { 4 | NIM_STRLIT_FLAG, "Hi, " };
static const NimStringV2 TM__DQXbay9bVPbJntbw5acsx2A_11 = {4, (NimStrPayload*)&TM__DQXbay9bVPbJntbw5acsx2A_10};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__DQXbay9bVPbJntbw5acsx2A_12 = { 1 | NIM_STRLIT_FLAG, "!" };
static const NimStringV2 TM__DQXbay9bVPbJntbw5acsx2A_13 = {1, (NimStrPayload*)&TM__DQXbay9bVPbJntbw5acsx2A_12};
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__DQXbay9bVPbJntbw5acsx2A_2 = {{18, (NimStrPayload*)&TM__DQXbay9bVPbJntbw5acsx2A_3}}
;
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__DQXbay9bVPbJntbw5acsx2A_4 = {{30, (NimStrPayload*)&TM__DQXbay9bVPbJntbw5acsx2A_5}}
;
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__DQXbay9bVPbJntbw5acsx2A_8 = {{30, (NimStrPayload*)&TM__DQXbay9bVPbJntbw5acsx2A_9}}
;
N_LIB_PRIVATE NimStringV2 name__examples_u1;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4315;
extern tySequence__Uepftf2kOzjjb8MCOsPz7Q gFuns__stdZexitprocs_u15;
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2) {
	int result;
	result = memcmp(a_p0, b_p1, ((size_t) (size_p2)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_u1753)(void* a_p0, void* b_p1, NI size_p2) {
	NIM_BOOL result;
	int T1_;
	T1_ = (int)0;
	T1_ = nimCmpMem(a_p0, b_p1, size_p2);
	result = (T1_ == ((NI32)0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NIM_BOOL result;
	NI alen;
	NI blen;
{	result = (NIM_BOOL)0;
	alen = a_p0.len;
	blen = b_p1.len;
	{
		if (!(alen == blen)) goto LA3_;
		{
			if (!(alen == ((NI)0))) goto LA7_;
			result = NIM_TRUE;
			goto BeforeRet_;
		}
LA7_: ;
		result = equalMem__system_u1753(((void*) ((&a_p0.p->data[((NI)0)]))), ((void*) ((&b_p1.p->data[((NI)0)]))), ((NI) (alen)));
		goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4315);
	return result;
}

N_LIB_PRIVATE void PreMainInner(void) {
	atmdotdotatsdotdotatsdotdotatsToolsatsnimminus2dot0dot2atslibatsstdatsexitprocsdotnim_Init000();
	atmdotdotatsdotdotatsdotdotatsToolsatsnimminus2dot0dot2atslibatsstdatssynciodotnim_Init000();
}

N_LIB_PRIVATE int cmdCount;
N_LIB_PRIVATE char** cmdLine;
N_LIB_PRIVATE char** gEnv;
N_LIB_PRIVATE void PreMain(void) {
#if 0
	void (*volatile inner)(void);
	inner = PreMainInner;
	atmdotdotatsdotdotatsdotdotatsToolsatsnimminus2dot0dot2atslibatsstdatssynciodotnim_DatInit000();
	atmdotdotatsdotdotatsdotdotatsToolsatsnimminus2dot0dot2atslibatssystemdotnim_Init000();
	(*inner)();
#else
	atmdotdotatsdotdotatsdotdotatsToolsatsnimminus2dot0dot2atslibatsstdatssynciodotnim_DatInit000();
	atmdotdotatsdotdotatsdotdotatsToolsatsnimminus2dot0dot2atslibatssystemdotnim_Init000();
	PreMainInner();
#endif
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
#if 0
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	(*inner)();
#else
	PreMain();
	NimMainInner();
#endif
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
	NimStringV2 T1_;
NIM_BOOL* nimErr_;
nimErr_ = nimErrorFlag();
	echoBinSafe(TM__DQXbay9bVPbJntbw5acsx2A_2, 1);
	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = readLine__stdZsyncio_u479(stdin);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	name__examples_u1 = T1_;
	{
		if (!(name__examples_u1.len == 0)) goto LA4_;
		echoBinSafe(TM__DQXbay9bVPbJntbw5acsx2A_4, 1);
	}
	goto LA2_;
LA4_: ;
	{
		if (!eqStrings(name__examples_u1, TM__DQXbay9bVPbJntbw5acsx2A_7)) goto LA7_;
		echoBinSafe(TM__DQXbay9bVPbJntbw5acsx2A_8, 1);
	}
	goto LA2_;
LA7_: ;
	{
		tyArray__24KAM9afIUgUaqBaEBB6r9bg T10_;
		T10_[0] = TM__DQXbay9bVPbJntbw5acsx2A_11;
		T10_[1] = name__examples_u1;
		T10_[2] = TM__DQXbay9bVPbJntbw5acsx2A_13;
		echoBinSafe(T10_, 3);
	}
LA2_: ;
	if (name__examples_u1.p && !(name__examples_u1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(name__examples_u1.p);
}
	eqdestroy___stdZexitprocs_u301(gFuns__stdZexitprocs_u15);
	BeforeRet_: ;
	nimTestErrorFlag();
}
}

